// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Test_Evaluacion.Web.Data;

namespace Test_Evaluacion.Web.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20210212003736_initialDB")]
    partial class initialDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Test_Evaluacion.Web.Data.Entities.Invoice", b =>
                {
                    b.Property<int>("InvoiceId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateProduct");

                    b.Property<int?>("InvoicesProductsId");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<decimal>("Price");

                    b.Property<int>("ProductId");

                    b.Property<int>("Quantity");

                    b.HasKey("InvoiceId");

                    b.HasIndex("InvoicesProductsId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("Test_Evaluacion.Web.Data.Entities.InvoicesProducts", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("Id");

                    b.ToTable("InvoicesProducts");
                });

            modelBuilder.Entity("Test_Evaluacion.Web.Data.Entities.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("InvoicesProductsId");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("ProductId");

                    b.HasIndex("InvoicesProductsId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Test_Evaluacion.Web.Data.Entities.Invoice", b =>
                {
                    b.HasOne("Test_Evaluacion.Web.Data.Entities.InvoicesProducts", "InvoicesProducts")
                        .WithMany("Invoices")
                        .HasForeignKey("InvoicesProductsId");
                });

            modelBuilder.Entity("Test_Evaluacion.Web.Data.Entities.Product", b =>
                {
                    b.HasOne("Test_Evaluacion.Web.Data.Entities.InvoicesProducts", "InvoicesProducts")
                        .WithMany("Products")
                        .HasForeignKey("InvoicesProductsId");
                });
#pragma warning restore 612, 618
        }
    }
}
